# Generated by Django 5.2.4 on 2025-08-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='actas.acta')),
            ],
        ),
    ]
