# Generated by Django 5.2.5 on 2025-08-06 12:29

import apps.gestiones.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('archivo_adjunto', models.FileField(upload_to='gestiones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg']), apps.gestiones.models.MaxFileSizeValidator(5242880)], verbose_name='Archivo adjunto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='actas.acta')),
            ],
        ),
    ]
