# Generated by Django 5.2.5 on 2025-08-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=15),
        ),
    ]
