# Generated by Django 5.2.4 on 2025-08-05 23:33

import django.core.validators
import django.db.models.deletion
import gestiones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('archivo_adjunto', models.FileField(upload_to='gestiones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg']), gestiones.models.MaxFileSizeValidator(5242880)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='actas.acta')),
            ],
        ),
    ]
